<a href="https://colab.research.google.com/github/briskicedteaa/Scientific-Visualization-for-Computational-Biology/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [28]:
df = pd.read_csv('/content/Ligands2.csv', sep =';' )
df = df.drop(columns=df.columns.difference(['Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency BEI', 'Ligand Efficiency SEI', 'Molecular Weight', 'Standard Value', 'AlogP']))
df = df.dropna()
df

,Molecular Weight,AlogP,Standard Value,Ligand Efficiency BEI,Ligand Efficiency LE,Ligand Efficiency LLE,Ligand Efficiency SEI
0,472.67,4.21,60.00,15.28,0.29,3.01,12.61
8,323.39,3.29,657.00,19.12,0.35,2.89,15.95
9,413.52,5.25,22300.00,11.25,0.20,-0.60,12.00
10,379.50,4.36,7.00,21.49,0.40,3.79,21.03
13,427.55,3.69,280.00,15.33,0.28,2.86,6.84
...,...,...,...,...,...,...,...
20124,351.35,3.88,1670.00,16.44,0.33,1.90,12.09
20125,433.49,7.26,7.10,18.80,0.36,0.89,22.05
20126,471.59,8.33,70.00,15.17,0.30,-1.18,19.36
20128,539.81,7.45,7.63,15.04,0.30,0.67,20.94
20131,455.41,5.43,308.90,14.30,0.32,1.08,11.72

In [44]:
X = df[['Molecular Weight', 'AlogP', 'Standard Value', 'Ligand Efficiency BEI', 'Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency SEI']]
X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
random_state=42
X_reduced = pca.fit_transform(X_scaled)

PC1 = X_reduced[:, 0]
PC2 = X_reduced[:, 1]

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter(x=PC1, y=PC2,
                 color=df['Molecular Weight'],
                 color_continuous_scale=['white', '#ff7dcf'],
                 title= "PCA of Acetylcholinterase Ligands:" f'Total Explained Variance: {total_var:.2f}%',
                 labels={'x': 'PC1', 'y': 'PC2'},
                 width=800, height=600,
                 render_mode='svg')

fig.update_traces(marker_line_color='black', marker_line_width=1)
fig.update_layout(coloraxis_showscale=False)
fig.show()

fig.write_html("pca_scatter_plot.html")

In [ ]:
import umap
reducer = umap.UMAP()

scaled_df_data = df

scaled_df_data.values
scaled_df_data = StandardScaler().fit_transform(scaled_df_data)

embedding = reducer.fit_transform(scaled_df_data)
embedding.shape

/usr/local/lib/python3.12/dist-packages/umap/spectral.py:548: UserWarning:

Spectral initialisation failed! The eigenvector solver
failed. This is likely due to too small an eigengap. Consider
adding some noise or jitter to your data.

Falling back to random initialisation!

(7999, 2)

In [45]:
scaled_df_data = df

scaled_df_data.values
scaled_df_data = StandardScaler().fit_transform(scaled_df_data)


embedding = reducer.fit_transform(scaled_df_data)
embedding.shape

n_components=2
random_state=42

UMAP1 = embedding[:, 0]
UMAP2 = embedding[:, 1]


fig = px.scatter(
    embedding[:, 0],
    embedding[:, 1],
)

fig = px.scatter(x=UMAP1, y=UMAP2,
                 color=df['Molecular Weight'],
                 color_continuous_scale=['white', '#ff7dcf'],
                 title='UMAP Of Acetylcholinterase Ligands',
                 labels={'x': 'UMAP1', 'y': 'UMAP2'},
                 width=800, height=600,
                 render_mode='svg')

fig.update_traces(marker_line_color='black', marker_line_width=1)
fig.update_layout(coloraxis_showscale=False)
fig.show()

fig.write_html("UMAP_scatter_plot.html")

/usr/local/lib/python3.12/dist-packages/umap/spectral.py:548: UserWarning:

Spectral initialisation failed! The eigenvector solver
failed. This is likely due to too small an eigengap. Consider
adding some noise or jitter to your data.

Falling back to random initialisation!

(7999, 2)
False

In [48]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

kmeans = KMeans(n_clusters=3, init='k-means++', n_init=10, random_state=42)
df['cluster'] = kmeans.fit_predict(df_scaled)

df.to_csv('Ligands2_with_kmeans.csv', index=False)

display(df.head())

,Molecular Weight,AlogP,Standard Value,Ligand Efficiency BEI,Ligand Efficiency LE,Ligand Efficiency LLE,Ligand Efficiency SEI,cluster
0,472.67,4.21,60.0,15.28,0.29,3.01,12.61,2
8,323.39,3.29,657.0,19.12,0.35,2.89,15.95,2
9,413.52,5.25,22300.0,11.25,0.20,-0.60,12.00,0
10,379.50,4.36,7.0,21.49,0.40,3.79,21.03,2
13,427.55,3.69,280.0,15.33,0.28,2.86,6.84,2

In [55]:
X = df[['Molecular Weight', 'AlogP', 'Standard Value', 'Ligand Efficiency BEI', 'Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency SEI']]
X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
random_state=42
X_reduced = pca.fit_transform(X_scaled)

PC1 = X_reduced[:, 0]
PC2 = X_reduced[:, 1]

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter(x=PC1,
                 y=PC2,
                 marginal_x='histogram',
                 marginal_y='histogram',
                 color=df['Molecular Weight'],
                 color_continuous_scale=['white', '#ff7dcf'],
                 title= "PCA of Acetylcholinterase Ligands:" f'Total Explained Variance: {total_var:.2f}%',
                 labels={'x': 'PC1', 'y': 'PC2'},
                 width=800, height=600,
                 render_mode='svg')

fig.update_traces(marker_line_color='black', marker_line_width=1)
fig.update_layout(coloraxis_showscale=False)
fig.show()

fig.write_html("pca_scatter_plot.html")